/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author uk023
 */
public class employee extends javax.swing.JFrame {
Connection con=null;
PreparedStatement pst =null;
String egen;
Statement s=null;
ResultSet r=null;

    /**
     * Creates new form employee
     */
    public employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        eid = new javax.swing.JTextField();
        ename = new javax.swing.JTextField();
        eaddress = new javax.swing.JTextField();
        edesig = new javax.swing.JTextField();
        ephone = new javax.swing.JTextField();
        esal = new javax.swing.JTextField();
        edoj = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        save = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        view = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(102, 102, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("Employee_ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 350, 100, 30);

        jLabel2.setBackground(new java.awt.Color(102, 102, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 420, 61, 16);

        jLabel3.setBackground(new java.awt.Color(102, 102, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("ADDRESS");
        jLabel3.setAlignmentX(2.0F);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 480, 103, 27);

        jLabel4.setBackground(new java.awt.Color(102, 102, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("DESIGNATION");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 550, 100, 16);

        jLabel5.setBackground(new java.awt.Color(102, 102, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("PHONE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 620, 90, 20);

        jLabel6.setBackground(new java.awt.Color(102, 102, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("SALARY");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 680, 80, 20);

        jLabel7.setBackground(new java.awt.Color(102, 102, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("GENDER");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 750, 61, 22);

        jLabel8.setBackground(new java.awt.Color(102, 102, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("JOINING DATE");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 800, 100, 30);
        getContentPane().add(eid);
        eid.setBounds(240, 350, 170, 30);
        getContentPane().add(ename);
        ename.setBounds(240, 410, 160, 22);
        getContentPane().add(eaddress);
        eaddress.setBounds(240, 480, 160, 22);

        edesig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edesigActionPerformed(evt);
            }
        });
        getContentPane().add(edesig);
        edesig.setBounds(240, 550, 160, 22);
        getContentPane().add(ephone);
        ephone.setBounds(240, 610, 160, 22);

        esal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esalActionPerformed(evt);
            }
        });
        getContentPane().add(esal);
        esal.setBounds(240, 680, 160, 22);
        getContentPane().add(edoj);
        edoj.setBounds(240, 820, 170, 22);

        buttonGroup1.add(male);
        male.setText("Male");
        getContentPane().add(male);
        male.setBounds(250, 750, 70, 25);

        buttonGroup1.add(female);
        female.setText("Female");
        getContentPane().add(female);
        female.setBounds(350, 750, 71, 25);

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "eno", "ename", "eaddress", "edesig", "ephone", "esal", "egen", "edob"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(570, 880, 599, 100);

        save.setBackground(new java.awt.Color(0, 0, 0));
        save.setForeground(new java.awt.Color(255, 255, 0));
        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(30, 880, 90, 25);

        reset.setBackground(new java.awt.Color(0, 0, 0));
        reset.setForeground(new java.awt.Color(255, 255, 0));
        reset.setText("reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(150, 880, 90, 25);

        update.setBackground(new java.awt.Color(0, 0, 0));
        update.setForeground(new java.awt.Color(255, 255, 0));
        update.setText("update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(260, 880, 110, 25);

        delete.setBackground(new java.awt.Color(0, 0, 0));
        delete.setForeground(new java.awt.Color(255, 255, 0));
        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(410, 880, 90, 25);

        view.setBackground(new java.awt.Color(0, 0, 0));
        view.setForeground(new java.awt.Color(255, 255, 0));
        view.setText("view");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        getContentPane().add(view);
        view.setBounds(150, 940, 180, 50);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 50, 90, 25);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\uk023\\OneDrive\\Desktop\\gympics\\trenazhernyj_zal_tyazhelaya_atletika_diski_118224_1920x1080.jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-10, 0, 1920, 1020);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project1","root","root");
             String query = "insert into emp7(eid,ename,eaddress,edesig,ephone,esal,egen,edoj)values(?,?,?,?,?,?,?,?)";
          PreparedStatement pst=con.prepareStatement(query);
           pst.setString(1, eid.getText()); 
          pst.setString(2, ename.getText());
           pst.setString(3, eaddress.getText());
           pst.setString(4, edesig.getText());
           pst.setString(5, ephone.getText());
           pst.setString(6, esal.getText());
           
            if(male.isSelected()){
                egen="male";
            }
            
             if(female.isSelected()){
                egen="female";
            }
            pst.setString(7,egen);
             pst.setString(8, edoj.getText());
             
          pst.executeUpdate();
           DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
                     JOptionPane.showMessageDialog(null, "Inserted Sucessfully!");
             
        }
         catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        
        String query="select eid,ename,eaddress,edesig,ephone,esal,egen,edoj from emp7";
        try
        {  con = DriverManager.getConnection("jdbc:mysql://localhost/project1","root","root");
            s=con.createStatement();
            r=s.executeQuery(query);
            jTable1.setModel(DbUtils.resultSetToTableModel(r));
        }
        catch(Exception e)
        {
        
        }
    }//GEN-LAST:event_viewActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
         eid.setText("");
        ename.setText("");
        eaddress.setText("");
        edesig.setText("");
        ephone.setText("");
        esal.setText("");
        buttonGroup1.clearSelection();
        edoj.setText("");

    }//GEN-LAST:event_resetActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         try{ 
            con = DriverManager.getConnection("jdbc:mysql://localhost/project1","root","root");
            int row=jTable1.getSelectedRow();
            String value=(jTable1.getModel().getValueAt(row,0).toString());
             
           String query="UPDATE emp7 SET eid=?,ename=?,eaddress=?,edesig=?,ephone=?,esal=?,egen=?,edoj=? where eid="+value;
        
            PreparedStatement pst=con.prepareStatement(query);
            pst.setString(1,eid.getText());
           pst.setString(2, ename.getText());
           pst.setString(3, eaddress.getText());
           pst.setString(4, edesig.getText());
           
           
           pst.setString(5, ephone.getText());
           pst.setString(6, esal.getText());
           
            if(male.isSelected()){
                egen="male";
            }
            
             if(female.isSelected()){
                egen="female";
            }
            pst.setString(7,egen);
             pst.setString(8, edoj.getText());
             
           
             
          pst.executeUpdate();
          DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
          model.setRowCount(0);
         
          JOptionPane.showMessageDialog(null, "Inserted Sucessfully!");  
          
    }                                         
           catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }                                    
    }//GEN-LAST:event_updateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int i = jTable1.getSelectedRow();
        TableModel model =jTable1.getModel();
        eid.setText(model.getValueAt(i,0).toString());
        ename.setText(model.getValueAt(i,1).toString());
        eaddress.setText(model.getValueAt(i,2).toString());
         edesig.setText(model.getValueAt(i,3).toString());
          ephone.setText(model.getValueAt(i,4).toString()); 
          esal.setText(model.getValueAt(i,5).toString());
           String sex = model.getValueAt(i,6).toString();
            if(sex.equals("male")){
                male.setSelected(true);
            }
            else{
                female.setSelected(true);
            }
            
          edoj.setText(model.getValueAt(i,7).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
             con = DriverManager.getConnection("jdbc:mysql://localhost/project1","root","root");
            int row=jTable1.getSelectedRow();
             String value=(jTable1.getModel().getValueAt(row,0).toString());
           String query="DELETE FROM emp7 where eid=?";
            PreparedStatement pst=con.prepareStatement(query);
          pst.setString(1,eid.getText()); 
           pst.executeUpdate();
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
         model.setRowCount(0);
         
          JOptionPane.showMessageDialog(null, "Deleted  Sucessfully!"); 
         
         
         
        
        }
         catch(Exception e){ 
            JOptionPane.showMessageDialog(null, e);
        }      
             
        
        
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         new homepage7().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void esalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esalActionPerformed

    private void edesigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edesigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edesigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton delete;
    private javax.swing.JTextField eaddress;
    private javax.swing.JTextField edesig;
    private javax.swing.JTextField edoj;
    private javax.swing.JTextField eid;
    private javax.swing.JTextField ename;
    private javax.swing.JTextField ephone;
    private javax.swing.JTextField esal;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton male;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    private javax.swing.JButton update;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
