package javaapplication1;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author uk023
 */
public class equip7 extends javax.swing.JFrame {
Connection con=null;
Statement s=null;
ResultSet r=null;
    /**
     * Creates new form equip7
     */
    public equip7() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ENO = new javax.swing.JTextField();
        ENAME = new javax.swing.JTextField();
        EPRICE = new javax.swing.JTextField();
        ECOUNT = new javax.swing.JTextField();
        EDOP = new javax.swing.JTextField();
        SAVE = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        reset = new javax.swing.JButton();
        VIEW = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("ENO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(770, 380, 85, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("ENAME");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(760, 450, 85, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("EPRICE");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(750, 540, 85, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("ECOUNT");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(750, 600, 85, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("EDOP");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(760, 680, 85, 30);

        ENO.setBackground(new java.awt.Color(0, 0, 0));
        ENO.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(ENO);
        ENO.setBounds(960, 380, 135, 22);

        ENAME.setBackground(new java.awt.Color(0, 0, 0));
        ENAME.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(ENAME);
        ENAME.setBounds(960, 460, 135, 22);

        EPRICE.setBackground(new java.awt.Color(0, 0, 0));
        EPRICE.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(EPRICE);
        EPRICE.setBounds(970, 540, 135, 22);

        ECOUNT.setBackground(new java.awt.Color(0, 0, 0));
        ECOUNT.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(ECOUNT);
        ECOUNT.setBounds(970, 610, 135, 22);

        EDOP.setBackground(new java.awt.Color(0, 0, 0));
        EDOP.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(EDOP);
        EDOP.setBounds(970, 690, 135, 22);

        SAVE.setBackground(new java.awt.Color(0, 0, 0));
        SAVE.setForeground(new java.awt.Color(255, 255, 0));
        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });
        jPanel1.add(SAVE);
        SAVE.setBounds(740, 790, 73, 25);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Equipments");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(710, 170, 350, 41);

        update.setBackground(new java.awt.Color(0, 0, 0));
        update.setForeground(new java.awt.Color(255, 255, 0));
        update.setText("update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(940, 790, 90, 25);

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ENO", "ENAME", "EPRICE", "ECOUNT", "EDOP"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(480, 860, 960, 110);

        reset.setBackground(new java.awt.Color(0, 0, 0));
        reset.setForeground(new java.awt.Color(255, 255, 0));
        reset.setText("reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(841, 790, 80, 25);

        VIEW.setBackground(new java.awt.Color(0, 0, 0));
        VIEW.setForeground(new java.awt.Color(255, 255, 0));
        VIEW.setText("view");
        VIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEWActionPerformed(evt);
            }
        });
        jPanel1.add(VIEW);
        VIEW.setBounds(1160, 790, 80, 25);

        delete.setBackground(new java.awt.Color(0, 0, 0));
        delete.setForeground(new java.awt.Color(255, 255, 0));
        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(1050, 790, 90, 25);

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 20, 80, 25);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\uk023\\OneDrive\\Desktop\\gympics\\164291951-fitness-wallpapers.jpg")); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 1920, 1010);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1925, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    
    
    
    
    
    
    
    
    
    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        // TODO add your handling code here:
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project1","root","root");
             String query = "insert into equipment(ENO,ENAME,EPRICE,ECOUNT,EDOP)values(?,?,?,?,?)";
          PreparedStatement pst=con.prepareStatement(query);
           pst.setString(1,ENO.getText()); 
          pst.setString(2, ENAME.getText());
           pst.setString(3, EPRICE.getText());
           pst.setString(4, ECOUNT.getText());
           pst.setString(5, EDOP.getText());
          
          pst.executeUpdate();
           
             JOptionPane.showMessageDialog(null, "Inserted Sucessfully!");
             
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_SAVEActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         
          try{ 
            con = DriverManager.getConnection("jdbc:mysql://localhost/project1","root","root");
            int row=jTable1.getSelectedRow();
            String value=(jTable1.getModel().getValueAt(row,0).toString());
             
           String query="UPDATE equipment SET ENO=?,ENAME=?,EPRICE=?,ECOUNT=?,EDOP=? where ENO="+value;
        
            PreparedStatement pst=con.prepareStatement(query);
            pst.setString(1,ENO.getText());
           pst.setString(2, ENAME.getText());
           pst.setString(3, EPRICE.getText());
           pst.setString(4, ECOUNT.getText());
           
           
           pst.setString(5, EDOP.getText());
          
             
          pst.executeUpdate();
          DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
          model.setRowCount(0);
    
          JOptionPane.showMessageDialog(null, "Inserted Sucessfully!");  
          
    }                                         
           catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }                                    
        
        
        
        
        
        
    }//GEN-LAST:event_updateActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        
             ENO.setText("");
        ENAME.setText("");
        EPRICE.setText("");
        ECOUNT.setText("");
        EDOP.setText("");
       
    }//GEN-LAST:event_resetActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
         int i = jTable1.getSelectedRow();
        TableModel model =jTable1.getModel();
        ENO.setText(model.getValueAt(i,0).toString());
        ENAME.setText(model.getValueAt(i,1).toString());
        EPRICE.setText(model.getValueAt(i,2).toString());
        ECOUNT.setText(model.getValueAt(i,3).toString());
          EDOP.setText(model.getValueAt(i,4).toString()); 
       
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void VIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEWActionPerformed
        // TODO add your handling code here:
        
           String query="select ENO,ENAME,EPRICE,ECOUNT,EDOP from equipment";
        try
        {  con = DriverManager.getConnection("jdbc:mysql://localhost/project1","root","root");
            s=con.createStatement();
            r=s.executeQuery(query);
            jTable1.setModel(DbUtils.resultSetToTableModel(r));
        }
        catch(Exception e)
        {
        
        }
    }//GEN-LAST:event_VIEWActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
             con = DriverManager.getConnection("jdbc:mysql://localhost/project1","root","root");
            int row=jTable1.getSelectedRow();
             String value=(jTable1.getModel().getValueAt(row,0).toString());
           String query="DELETE FROM equipment where ENO=?";
            PreparedStatement pst=con.prepareStatement(query);
          pst.setString(1,ENO.getText()); 
           pst.executeUpdate();
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
         model.setRowCount(0);
         
          JOptionPane.showMessageDialog(null, "Deleted  Sucessfully!"); 
         
         
         
        
        }
         catch(Exception e){ 
            JOptionPane.showMessageDialog(null, e);
        }      
        
        
        
        
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         new homepage7().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(equip7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(equip7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(equip7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(equip7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new equip7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ECOUNT;
    private javax.swing.JTextField EDOP;
    private javax.swing.JTextField ENAME;
    private javax.swing.JTextField ENO;
    private javax.swing.JTextField EPRICE;
    private javax.swing.JButton SAVE;
    private javax.swing.JButton VIEW;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton reset;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
