
package javaapplication1;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author uk023
 */
public class memberdetails extends javax.swing.JFrame {
Connection con=null;
String gender;
Statement s=null;
 PreparedStatement pst=null;
        ResultSet r=null;
    /**
     * Creates new form memberdetails
     */
    public memberdetails() {
        initComponents();
    }
       
   
        /**
     * This method is called from within the constr
     * 
     * uctor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mname = new javax.swing.JTextField();
        maddress = new javax.swing.JTextField();
        mphone = new javax.swing.JTextField();
        mweight = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        save = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        mid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        view = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        employeeno = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("BACK");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 0));
        setMinimumSize(new java.awt.Dimension(87877, 878778));
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1520, 440, 70, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("ADDRESS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1510, 510, 90, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("PHONE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1510, 600, 80, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("WEIGHT");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1520, 670, 70, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("GENDER");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1520, 730, 70, 20);

        mname.setBackground(new java.awt.Color(0, 0, 0));
        mname.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(mname);
        mname.setBounds(1660, 430, 192, 40);

        maddress.setBackground(new java.awt.Color(0, 0, 0));
        maddress.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(maddress);
        maddress.setBounds(1660, 500, 192, 40);

        mphone.setBackground(new java.awt.Color(0, 0, 0));
        mphone.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(mphone);
        mphone.setBounds(1660, 590, 192, 40);

        mweight.setBackground(new java.awt.Color(0, 0, 0));
        mweight.setForeground(new java.awt.Color(255, 255, 0));
        mweight.setMinimumSize(new java.awt.Dimension(69009, 2238990));
        getContentPane().add(mweight);
        mweight.setBounds(1670, 670, 192, 30);

        male.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(male);
        male.setForeground(new java.awt.Color(255, 255, 0));
        male.setText("MALE");
        getContentPane().add(male);
        male.setBounds(1670, 730, 70, 25);

        female.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(female);
        female.setForeground(new java.awt.Color(255, 255, 0));
        female.setText("FEMALE");
        getContentPane().add(female);
        female.setBounds(1780, 730, 73, 25);

        save.setBackground(new java.awt.Color(0, 0, 0));
        save.setForeground(new java.awt.Color(255, 255, 0));
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(1470, 850, 80, 30);

        reset.setBackground(new java.awt.Color(0, 0, 0));
        reset.setForeground(new java.awt.Color(255, 255, 0));
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(1580, 850, 80, 30);

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setForeground(new java.awt.Color(255, 255, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "mid", "mname", "maddress", "mphone", "mweight", "gender", "Trainer_id"
            }
        ));
        jTable1.setMinimumSize(new java.awt.Dimension(436787, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 870, 710, 90);

        update.setBackground(new java.awt.Color(0, 0, 0));
        update.setForeground(new java.awt.Color(255, 255, 0));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(1690, 850, 80, 30);

        delete.setBackground(new java.awt.Color(0, 0, 0));
        delete.setForeground(new java.awt.Color(255, 255, 0));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(1790, 850, 90, 30);

        mid.setBackground(new java.awt.Color(0, 0, 0));
        mid.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(mid);
        mid.setBounds(1660, 370, 190, 30);

        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText("Member_ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1510, 380, 71, 20);

        view.setBackground(new java.awt.Color(0, 0, 0));
        view.setForeground(new java.awt.Color(255, 255, 0));
        view.setText("VIEW");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        getContentPane().add(view);
        view.setBounds(1620, 920, 120, 40);

        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("TRAINER_ID");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1520, 790, 90, 20);

        employeeno.setBackground(new java.awt.Color(0, 0, 0));
        employeeno.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(employeeno);
        employeeno.setBounds(1680, 780, 160, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 0));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 20, 120, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\uk023\\OneDrive\\Desktop\\gympics\\wp2356158.jpg")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1920, 1130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
         try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/project1","root","root");
             String query = "insert into members(mid,mname,maddress,mphone,mweight,gender,employeeno)values(?,?,?,?,?,?,?)";
          PreparedStatement pst=con.prepareStatement(query);
           pst.setString(1,mid.getText()); 
          pst.setString(2, mname.getText());
           pst.setString(3, maddress.getText());
           pst.setString(4, mphone.getText());
           pst.setString(5, mweight.getText());

           
            if(male.isSelected()){
                gender="male";
            }
            
             if(female.isSelected()){
                gender="female";
            }
            pst.setString(6,gender);

               pst.setString(7, employeeno.getText());
            
             
          pst.executeUpdate();
           DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
        
             JOptionPane.showMessageDialog(null, "Inserted Sucessfully!");
             
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_saveActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code her:
       mid.setText("");
        mname.setText("");
        maddress.setText("");
        mphone.setText("");
        mweight.setText("");
        
        buttonGroup1.clearSelection();
      
        employeeno.setText("");
      
    }//GEN-LAST:event_resetActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int i = jTable1.getSelectedRow();
        TableModel model =jTable1.getModel();
        mid.setText(model.getValueAt(i,0).toString());
        mname.setText(model.getValueAt(i,1).toString());
        maddress.setText(model.getValueAt(i,2).toString());
         mphone.setText(model.getValueAt(i,3).toString());
          mweight.setText(model.getValueAt(i,4).toString()); 
         
         String sex = model.getValueAt(i,5).toString();
            if(sex.equals("male")){
                male.setSelected(true);
            }
            else{
                female.setSelected(true);
            }
            
         
        employeeno.setText(model.getValueAt(i,6).toString());
     
    }//GEN-LAST:event_jTable1MouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{ 
            con = DriverManager.getConnection("jdbc:mysql://localhost/project1","root","root");
            int row=jTable1.getSelectedRow();
            String value=(jTable1.getModel().getValueAt(row,0).toString());
             
           String query="UPDATE members SET mid=?,mname=?,maddress=?,mphone=?,mweight=?,gender=?,employeeno=? where mid="+value;
        
            PreparedStatement pst=con.prepareStatement(query);
            pst.setString(1,mid.getText());
           pst.setString(2, mname.getText());
           pst.setString(3, maddress.getText());
           pst.setString(4, mphone.getText());
           
           
           pst.setString(5, mweight.getText());
          
           
            if(male.isSelected()){
                gender="male";
            }
            
             if(female.isSelected()){
                gender="female";
            }
            pst.setString(6,gender);
            
             pst.setString(7, employeeno.getText());
            
           
             
          pst.executeUpdate();
          DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
          model.setRowCount(0);
         
          JOptionPane.showMessageDialog(null, "Inserted Sucessfully!");  
          
    }                                         
           catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }                                    
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
             con = DriverManager.getConnection("jdbc:mysql://localhost/project1","root","root");
            int row=jTable1.getSelectedRow();
             String value=(jTable1.getModel().getValueAt(row,0).toString());
           String query="DELETE FROM members where mid=?";
            PreparedStatement pst=con.prepareStatement(query);
          pst.setString(1,mid.getText()); 
           pst.executeUpdate();
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
         model.setRowCount(0);
          System.out.println("  items were removed from PALLET");
          JOptionPane.showMessageDialog(null, "Deleted  Sucessfully!"); 
         
         
         
        
        }
         catch(Exception e){ 
            JOptionPane.showMessageDialog(null, e);
        }      
             
            
        
    }//GEN-LAST:event_deleteActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
       String query="select mid,mname,maddress,mphone,mweight,gender,employeeno from members";
        try
        {  con = DriverManager.getConnection("jdbc:mysql://localhost/project1","root","root");
            s=con.createStatement();
            r=s.executeQuery(query);
            jTable1.setModel(DbUtils.resultSetToTableModel(r));
        }
        catch(Exception e)
        {
        
        }
        
    }//GEN-LAST:event_viewActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new homepage7().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(memberdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(memberdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(memberdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(memberdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           
                new memberdetails().setVisible(true);
                 
         
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton delete;
    private javax.swing.JTextField employeeno;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField maddress;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mid;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField mphone;
    private javax.swing.JTextField mweight;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    private javax.swing.JButton update;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
